"""
Django settings for thriftshop project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-c5xv+k^&o74x8g=b=zn63vjr62^0jf^d$510z9wm9h%uj(d2gl"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True  # Set False in production

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']  # Update with your domain when deploying

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "shop",

]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "thriftshop.urls"

TEMPLATES_DIR = BASE_DIR / "templates"  
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],  # Ensure this is set correctly
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = "thriftshop.wsgi.application"


# Database Configuration (Default: SQLite, Change to PostgreSQL for production)
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

"""
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "your_db_name",
        "USER": "your_db_user",
        "PASSWORD": "your_db_password",
        "HOST": "localhost",
        "PORT": "5432",
    }
}
"""

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

LANGUAGE_CODE = "en-us"
TIME_ZONE = "Asia/Kathmandu" 
USE_I18N = True
USE_TZ = True


STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]  
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGIN_URL = '/login/'

# Authentication settings
LOGIN_URL = 'login'  # URL name for login page (matches your login_view)
LOGIN_REDIRECT_URL = 'home'  # Redirect after login (matches your home view)
LOGOUT_REDIRECT_URL = 'login'  # Redirect after logout (matches your logout_view)

# Khalti Configuration
KHALTI_PUBLIC_KEY = "90103e2378254312801086a54bd6390f"  # Sandbox public key
KHALTI_SECRET_KEY = "5a30c11b81904852b0454d729f573b3d"  # Sandbox secret key
KHALTI_INITIATE_URL = "https://dev.khalti.com/api/v2/epayment/initiate/"  # Sandbox initiate URL
KHALTI_VERIFY_URL = "https://dev.khalti.com/api/v2/epayment/lookup/"  # Corrected to lookup endpoint

KHALTI_RETURN_URL = "http://localhost:8000/payment/success/"

# Website URL (replace with your actual domain)
WEBSITE_URL = "http://localhost:8000/"  # For local testing

