# Generated by Django 5.1.3 on 2025-04-28 16:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_product_sizes"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Category",
        ),
    ]
