# Generated by Django 5.1.3 on 2025-04-28 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_delete_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trendingclothes",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trending",
                to="shop.product",
            ),
        ),
    ]
