# Generated by Django 5.1.3 on 2025-04-28 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0005_payment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="total_price",
            new_name="total",
        ),
        migrations.AddField(
            model_name="order",
            name="billing_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_address",
            field=models.TextField(blank=True, null=True),
        ),
    ]
