# Generated by Django 5.1.3 on 2025-04-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0006_rename_total_price_order_total_order_billing_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("S", "Small"),
                    ("M", "Medium"),
                    ("L", "Large"),
                    ("XL", "Extra Large"),
                    ("XXL", "Double XL"),
                ],
                max_length=4,
                null=True,
            ),
        ),
    ]
