# Generated by Django 5.1.3 on 2025-04-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0007_alter_orderitem_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
